config/routes.rb
Rails.application.routes.draw do
  root to: 'questions#index'
  get :find, to: "searches#find"
  devise_for :users, controllers: { omniauth_callbacks: 'omni_callbacks' }
  resources :searches, :answers, :questions, :users
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  include PgSearch
  has_many :answers, :dependent => :destroy
  belongs_to :user
  default_scope { order(created_at: :DESC) }
  pg_search_scope :search, :against => [:title, :body]
end

app/models/search.rb
class Search < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :trackable, :validatable

  devise :omniauthable, omniauth_providers: [:google_oauth2]

  has_many :questions
  has_many :answers    

  def self.from_omniauth(access_token)
    user = User.where(email: access_token.info['email']).first
    # When user does not exist
    unless user
        user = User.create(name: data['name'],
        email: data['email'],
        password: Devise.friendly_token[0,20]
        )
    end
    return user
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @answer = Answer.new
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(answer_params)
    question = Question.find(@answer.question_id)
    respond_to do |format|
      if @answer.save
        format.html { redirect_to question, notice: 'Answer was successfully created.' }
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { render :new }
        format.json { render json: question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    question = Question.find(@answer.question_id)

    respond_to do |format|
      format.html { redirect_to question, notice: 'Answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:body, :user_id, :question_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception, if: Proc.new { |c| c.request.format != 'application/json' }
  protect_from_forgery with: :null_session, if: Proc.new { |c| c.request.format == 'application/json' }
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/omni_callbacks_controller.rb
class OmniCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
      @user = User.from_omniauth(request.env['omniauth.auth'])
      if @user.persisted?
        flash[:notice] = "You are signed in as #{@user.name} (#{@user.email}). You can change your name under: Account > Edit my account.".html_safe
        sign_in_and_redirect @user, event: :authentication
      else
        session['devise.google_data'] = request.env['omniauth.auth'].except(:extra) # Removing extra as it can overflow some session stores
        redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
      end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
     @limit = 5
     @questions = Question.page(params[:page]).per(@limit)
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @answer = Answer.new
    @answers = Question.find(params[:id]).answers
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:title, :body, :user_id)
    end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_search, only: [:show, :edit, :update, :destroy]

  def find
    render :json => Question.search(params[:query]).to_json
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_search
      @search = Search.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def search_params
      params.fetch(:search, {})
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  before_action :authenticate_user!  
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def emd content
    Markdown.new(content).to_html.html_safe
  end

  def calculate_index page, index, limit
    if page
      (limit * (page.to_i - 1 )) + (index +1)
    else 
      index +1
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/answers/_form.html.erb
<%= form_with(model: answer, local: true) do |form| %>
  <% if answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_area :body, class: "width-70p", rows: "5" %>
  </div>

  <div class="field">
    <%= form.hidden_field :user_id, value: current_user.id %>
    <%= form.hidden_field :question_id, value: this_question.id %>
  </div>

  <div class="actions">
    <%= form.submit "Add comment", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing Answer</h1>

<%= render 'form', answer: @answer, this_question: da_question %>

app/views/answers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Answers</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>User</th>
      <th>Question</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= answer.body %></td>
        <td><%= answer.user_id %></td>
        <td><%= answer.question_id %></td>
        <td><%= link_to 'Show', answer %></td>
        <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
        <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Answer', new_answer_path %>

app/views/answers/new.html.erb
<h1>New Answer</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'Back', answers_path %>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @answer.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @answer.user_id %>
</p>

<p>
  <strong>Question:</strong>
  <%= @answer.question_id %>
</p>

<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>

app/views/layouts/_icons_tags.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="/icons/apple-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="/icons/apple-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="/icons/apple-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="/icons/apple-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="/icons/apple-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="/icons/apple-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/icons/apple-icon-180x180.png">
<link rel="icon" type="image/png" sizes="192x192"  href="/icons/android-icon-192x192.png">
<link rel="icon" type="image/png" sizes="32x32" href="/icons/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="96x96" href="/icons/favicon-96x96.png">
<link rel="icon" type="image/png" sizes="16x16" href="/icons/favicon-16x16.png">
<link rel="manifest" href="/icons/manifest.json">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="/icons/ms-icon-144x144.png">
<meta name="theme-color" content="#ffffff">

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_mobile_tags.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, 
      minimum-scale=1, user-scalable=no, viewport-fit=cover">
<meta name="apple-mobile-web-app-title" content="Cookpad Q&A" />

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to "Post a question", new_question_path %> </li>
  <li><%= link_to "Search", searches_path, "data-turbolinks": false %> </li>
  <%= render "layouts/dropdowns/account" %>
<% else %>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
  
  <!-- <li role="presentation" class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
        Home <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
         
        <li role="separator" class="divider"></li>
    </ul>
  </li> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Cookpad Q&A" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Cookpad Q&A" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= render "layouts/mobile_tags" %>
    <%= render "layouts/icons_tags" %>  
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <br>
      <div class="container">
        <%= render 'layouts/messages' %>
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/layouts/dropdowns/_account.html.erb
<li role="presentation" class="dropdown">
  <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
    Account <span class="caret"></span>
  </a>
  <ul class="dropdown-menu">
      <li><%= link_to 'About Q&A', page_path('about') %></li> 
      <li><%= link_to 'Edit my account', edit_user_registration_path %></li>        
      <li role="separator" class="divider"></li>
      <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
  </ul>
</li>

app/views/pages/about.html.erb
<ol class="breadcrumb">
  <li><a href="/">All questions</a></li>
  <li class="active">About Q&A</li>
</ol>

<%= render "pages/about" %>

app/views/questions/_form.html.erb
<%= form_with(model: question, local: true) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %> <br>
    <%= form.text_field :title, class:"width-70p" %>
  </div>

  <div class="field">
    <br>
    <%= form.text_area :body, class:"width-70p", rows:"6" %>
  </div>

  <div class="field">
    <%= form.hidden_field :user_id, :value => current_user.id %>
  </div>
  <hr>
  <div class="actions">
    <%= form.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<ol class="breadcrumb">
  <li><a href="/">All questions</a></li>
  <li><%= link_to @question.title[0..35] + " ....", @question %></li>
  <li class="active">Editing question</li>
</ol>

<h4>Editing Question</h4>
<hr>
<%= render 'form', question: @question %>

app/views/questions/index.html.erb
<p>Welcome <%= current_user.name %>!</p>

<div class="row">
  <div class="col-xs-6 col-sm-6 col-md-9">
    <h4><u>All Questions</u></h4>
    <p class="italic grey">every question posted in Q&A</p>
  </div>
  <div class="col-xs-6 col-sm-6 col-md-3">
    <%= link_to  "New Question", new_question_path, class: "btn btn-success float_right", title: "Post a question" %>
    <%= link_to  "<i class='fa fa-search'></i>".html_safe, searches_path, class: "btn btn-default float_right margin-right-5", title: "Find a question", "data-turbolinks": false %>
  </div>
</div>

<hr>
<% @questions.each_with_index do |question, index| %>
  <h4><%= calculate_index(params[:page], index, @limit) %>. <%= link_to question.title, question %></h4> 
  <p><%= question.answers.count %> comments </p>
  <p>Posted <%= time_ago_in_words(question.created_at) %> ago, by <span class="dotted"><%= question.user.name %></span></p>
  <br>
<% end %>

<%= paginate @questions %>

app/views/questions/new.html.erb
<ol class="breadcrumb">
  <li><a href="/">All questions</a></li>
  <li class="active">New question</li>
</ol>

<h4><u>New Question</u></h4>
<p class="grey italic">You may use markdown in your question title and content.</p>
<hr>
<%= render 'form', question: @question %>

app/views/questions/show.html.erb
<ol class="breadcrumb">
  <li><a href="/">All questions</a></li>
  <li class="active"><%= @question.title[0..35] + " ...." %></li>
</ol>

<h3>
  <%= emd(@question.title) %>
</h3>
<hr>

<div class="panel panel-info">
  <div class="panel-heading"><p><b><%= @question.user.name %></b> posted <%= time_ago_in_words(@question.created_at) %> ago <%= link_to 'Edit question', edit_question_path(@question)  if current_user.id == @question.user.id %> <%= link_to '| Delete question', @question, method: :delete, data: { confirm: 'Are you sure?' } if current_user.id == @question.user.id%></p></div>
  <div class="panel-body">
    <%= emd(@question.body) %>
  </div>
</div>

<hr>

<% if @answers.count != 0 %>
  <% @answers.each do |answer| %>
    <div class="panel panel-default">
      <div class="panel-heading">
          <b><%= answer.user.name %></b> commented <%= time_ago_in_words(answer.created_at) %> ago
            <%= link_to 'Edit comment', edit_answer_path(answer, this_question: @question)  if current_user.id == answer.user.id%> 
            <%= link_to '| Delete comment', answer, method: :delete, data: { confirm: 'Are you sure?' } if current_user.id == answer.user.id %>
      </div>
      
      <div class="panel-body">
       <%= emd(answer.body) %>
      </div>
    </div>
    <hr>
  <% end %>

  <b>There is a total of <%= @answers.count %> comment(s).</b>
  <p class='grey'>Add a comment. You may use markdown in your comment.</p>
  <%= render 'answers/form', answer: @answer, this_question: @question %>
<% else %>

  <hr>
  <b>There is no comment yet. Be the first to comment.</b>
  <p class='grey'>You may use markdown in your comment.</p>
  <%= render 'answers/form', answer: @answer, this_question: @question %>
<% end %>

app/views/searches/_form.html.erb
<%= form_with(model: search, local: true) do |form| %>
  <% if search.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(search.errors.count, "error") %> prohibited this search from being saved:</h2>

      <ul>
      <% search.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/searches/edit.html.erb
<h1>Editing Search</h1>

<%= render 'form', search: @search %>

<%= link_to 'Show', @search %> |
<%= link_to 'Back', searches_path %>

app/views/searches/index.html.erb
<ol class="breadcrumb">
  <li><a href="/">All questions</a></li>
  <li class="active">Search a question</li>
</ol>

<h4><u>Questions finder</u></h4>
<p class="grey italic">Suggestions: best sites, cookpad, eat</p>
<hr>
<div id="search_bar"></div>
<%= vue_component "search_bar" %> 

app/views/searches/new.html.erb
<h4>New Search</h4>

<%= render 'form', search: @search %>

<%= link_to 'Back', searches_path %>

app/views/searches/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_search_path(@search) %> |
<%= link_to 'Back', searches_path %>